const BoardMeasures = {
  SQUARE_SIZE: 7.273,
  MODEL_PLAYER: 0,
  MODEL_PROPERTY: 1,
  MODEL_PLAYER_OFFSET: 0.2,
  MODEL_PLAYER_MARGIN: 0.1,
  MODEL_PROPERTY_TOP_MARGIN: 0.39,
  MODEL_PROPERTY_LEFT_MARGIN: 0.37,
  MODEL_PROPERTY_MARGIN: 0.24,
  MODEL_PROPERTY_LEFT_OFFSET: 0.05,
  TILE_MAX: 39,
};

export const BoardSizes = {
  SIZE: 11,
  SIDE_TOP: 2,
  SIDE_LEFT: 1,
  SIDE_RIGHT: 3,
  SIDE_BOTTOM: 0,
};

export default BoardMeasures;
