/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/board.gltf");
  const { children, ...nativeProps } = props;
  return (
    <group ref={group} {...nativeProps} dispose={null}>
      <mesh geometry={nodes.board.geometry} 
      // material={materials.DefaultMaterial}
      >
        {children}
      </mesh>
    </group>
  );
}

useGLTF.preload("/board.gltf");
